name: Get Core File
on: [pull_request]
jobs:
  Example:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout test-GHA
        uses: actions/checkout@v2
        with:
          path: test-GHA
      - name: build and run
        shell: bash
        run: |
          cd test-GHA
          g++ test_segfault.cpp -o segfault
          ulimit -c unlimited
          ./segfault
      - name: list files
        run: |
          ls ${{ github.workspace }}