name: Get Core File
on: [pull_request]
jobs:
  Example:
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: checkout test-GHA
        uses: actions/checkout@v2
        with:
          path: test-GHA
      - name: build and run
        shell: bash
        run: |
          cd test-GHA
          g++ test_segfault.cpp -o segfault
          ulimit -c unlimited
          ulimit -c
          echo "Current directory:"
          pwd
          echo "Before running"
          ls
          sh -c "./segfault"
          echo "After running"
          ls
      - name: list files
        if: always()
        run: |
          echo "find core"
          find /var -name "core"
          echo "ls test-GHA"
          ls test-GHA
          echo "ls /var"
          ls /var
          echo "ls /var/crash"
          ls /var/crash
      - name: upload core file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: crash
          path: .
