name: Get Core File
on: [pull_request]
jobs:
  Example:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout test-GHA
        uses: actions/checkout@v2
        with:
          path: test-GHA
      - name: build and run
        shell: bash
        run: |
          cd test-GHA
          g++ test_segfault.cpp -o segfault
          ulimit -c unlimited
          echo "Current directory:"
          pwd
          echo "Before running"
          ls
          ./segfault
          echo "After running"
          ls
          chmod -R +r /cores/*
      - name: list files
        run: ls test-GHA
      - name: upload core file
        uses: actions/upload-artifact@v2
        with:
          name: crash
          path: /cores