name: Get Core File
on: [pull_request]
jobs:
  Example:
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: checkout test-GHA
        uses: actions/checkout@v2
        with:
          path: test-GHA
      - name: build and run
        shell: bash
        run: |
          cd test-GHA
          g++ test_segfault.cpp -o segfault
          sudo ulimit -c unlimited
          echo "Current directory:"
          pwd
          echo "Before running"
          ls
          ./segfault
          echo "After running"
          ls
      - name: list files
        if: always()
        run: |
          echo "ls ."
          ls test-GHA
          echo "ls .."
          ls ..
      - name: upload core file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: crash
          path: .
